Us012   add new role to existing job family and band
AlexMcC02/TeamTwo-FrontEnd pull request #16
Opened 2023-08-01 10:44 UTC by gibpaul

2023-08-02 09:54 UTC, ConnMeehan approved these changes

2023-08-02 09:56 UTC, philipwilson5 approved these changes

2023-08-02 13:29 UTC, shaunganley requested changes
good start, some comments about routes that aren't required and missing tests

2023-08-02 13:29 UTC, shaunganley commented on controller/BandController.ts
> +    app.get('/band', async (req: Request, res: Response) => {
not required

2023-08-02 13:29 UTC, shaunganley commented on app.ts
> +require("./controller/CapabilityController")(app)
not required

2023-08-02 13:29 UTC, shaunganley commented on controller/CapabilityController.ts
> +    app.get('/capability', async (req: Request, res: Response) => {
not required

2023-08-02 13:29 UTC, shaunganley commented on controller/JobRoleController.ts
> +            res.render('add-jobrole')
when an error is thrown you're not pre-populating the dropdown lists again or passing through the data that had been submitted on the form

2023-08-02 13:29 UTC, shaunganley commented on model/JobRoleCorrect.ts
> +export class JobRoleCorrect {
not a good name for the class

2023-08-02 13:29 UTC, shaunganley commented on service/BandService.ts
> +        const response = await axios.get('http://localhost:8080/api/band')
pass 'http://localhost:8080' through as an environment variable for we can set it to the AWS URL when deployed

2023-08-02 13:29 UTC, shaunganley commented on service/CapabilityService.ts
> +        const response = await axios.get('http://localhost:8080/api/capabilities')
pass 'http://localhost:8080' through as an environment variable for we can set it to the AWS URL when deployed

2023-08-02 13:29 UTC, shaunganley commented on service/CapabilityService.ts
> +        const response = await axios.get('http://localhost:8080/api/capabilities')
looks like this is already done in job role service: process.env.UI_URL

2023-08-02 13:29 UTC, shaunganley commented on service/BandService.ts
> +        const response = await axios.get('http://localhost:8080/api/band')
looks like this is already done in job role service: process.env.UI_URL

2023-08-02 13:29 UTC, shaunganley commented on test/unit/controller/JobRoleControllerTests.ts
> +                    specification: "Works on stuff"
you're not actually returning an error here

2023-08-02 13:29 UTC, shaunganley commented on test/unit/controller/JobRoleControllerTests.ts
> +                    .post('/add-jobrole').set('Accept', 'application/json').expect(302)
you don't redirect in case of an error, you're reloading the same view

2023-08-02 13:29 UTC, shaunganley commented on test/unit/controller/JobRoleControllerTests.ts
> +            it('should render the view-jobrole-specification view with job role data', async () => {
missing a test for error scenario

2023-08-02 13:29 UTC, shaunganley commented on test/unit/controller/JobRoleControllerTests.ts
> +        it('should render the add-jobrole view', async () => {
missing a test for error scenario

2023-08-02 13:29 UTC, shaunganley commented on test/unit/service/JobRoleServiceTests.ts
> +        it('should throw an error if the job role is missing a required field', async () => {
you're not mocking out your validator class so this test is also testing your validator class. please mock the validator and update tests for successful and unsuccessful validation

2023-08-02 13:29 UTC, shaunganley commented on validator/JobRoleValidator.ts
> +module.exports.validateJobRole = function(jobRole: JobRoleCorrect): string | null {
needs unit tests

2023-08-03 11:14 UTC, shaunganley requested changes
still needs comments addressed and validator tests

2023-08-03 11:14 UTC, shaunganley commented on controller/JobRoleController.ts
> +            res.render('add-jobrole')
comment still needs addressed

2023-08-03 11:14 UTC, shaunganley commented on model/JobRoleAdd.ts
> +    name?: string
why is this optional?

2023-08-03 11:14 UTC, shaunganley commented on test/unit/controller/JobRoleControllerTests.ts
> +
shouldn't be commented

2023-08-03 14:39 UTC, shaunganley approved these changes

2023-08-03 15:15 UTC, merged