Us002 UI tests
AlexMcC02/TeamTwo-FrontEnd pull request #6
Opened 2023-07-25 11:00 UTC by philipwilson5

2023-07-28 08:48 UTC, AlexMcC02 commented on .github/workflows/node.js.yml
cache: "npm" should be cache: 'npm'

2023-07-28 08:49 UTC, AlexMcC02 requested changes
Address the changes and we're good to go.

2023-07-28 08:49 UTC, AlexMcC02 commented on app.ts
Why remove export?

2023-07-28 09:00 UTC, AlexMcC02 approved these changes
Looks good!

2023-08-01 08:14 UTC, ConnMeehan approved these changes

2023-08-01 08:14 UTC, merged